#!/usr/bin/env bash
# Copyright ©2025 by Alienkrishn [Anon4You] All rights reserved.  🌎 🌍 🌏 🌐 🗺
#
# https://t.me/nullxvoid
# Githuh.com/Anon4You
#
#opyright (c) 2025 Alienkrishn
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
# COLORS
W="\e[0m"
R="\e[31m"
G="\e[32m"
Y="\e[33m"
B="\e[34m"
dirPATH="${PREFIX}/var/apktool/"

if [[ -e $dirPATH/$(basename $0).jar ]]
then
  exec $(command -v java) -jar $dirPATH/$(basename $0).jar ${@:1}
else
  echo -en $R"E:$W $(basename $0) PATH missing ...$Y Aborting.$W"
  exit 1
fi 
####::: REPORT ISSUES AT https://t.me/Alienkrishn :::####
